web:
  build: .
  working_dir: /go/src/announcer
  environment:
    - API_TOKEN=${API_TOKEN}
  links:
    - redisdb
redisdb:
  image: redis
  command: redis-server --appendonly yes
  volumes:
    - ./data:/data
  ports:
    - "6379:6379"
